apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T13:00:06Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "136500"
  uid: 0d1105ba-cc95-48b4-8850-e9222d7537c6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.107.107.79
  clusterIPs:
  - 10.107.107.79
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30392
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
